# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: books
on:
 workflow_dispatch:
 schedule:
   - cron: "3 */1 * * *"
permissions: write-all
env: # Or as an environment variable
      DB_URL: ${{ secrets.DB_URL }}
      K_U: ${{ secrets.K_U }}
      K_P: ${{ secrets.K_P}}
      AMZKEY: ${{ secrets.AMZKEY}}
      AMZSECRET: ${{ secrets.AMZSECRET}}
      THROTTLE: ${{ secrets.THROTTLE}}
      DEPLOYED: ${{ secrets.DEPLOYED}}
      DEBUG: ${{ secrets.DEBUG}}
      PULL: ${{ secrets.PULL}}
jobs:
  cron:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup WARP
      uses: fscarmen/warp-on-actions@v1.3
    - name: Install Virtual Server
      run: |
        sudo apt-get install x11-utils
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi
    - name: execute py script # run main.py
      run: python kindle.py
    
    # - name: commit files
    #   run: |
    #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #     git config user.name "github-actions[bot]"
    #     git add -A
    #     git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
    # - name: push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: ${{ github.ref }}